/*
 * kunabi-main-static.c — Entry point for fully static kunabi binary.
 *
 * Like kunabi-main.c but with:
 *   - dlopen/dlsym stubs (no dynamic linker in static builds)
 *   - Explicit Sforeign_symbol registration for all FFI functions
 *
 * Boot files are embedded as C byte arrays via generated .h files.
 * FFI symbol registration is generated by build-static-artifacts.ss
 * into kunabi_ffi_symbols.h.
 */

#define _GNU_SOURCE
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <unistd.h>
#include <sys/mman.h>
#include "scheme.h"
#include "kunabi_program.h"
#include "kunabi_petite_boot.h"
#include "kunabi_scheme_boot.h"
#include "kunabi_kunabi_boot.h"

/* ── dlopen stubs for static builds ────────────────────────────────── */
void *dlopen(const char *f, int fl) { (void)f; (void)fl; return (void*)1; }
void *dlsym(void *h, const char *s) { (void)h; (void)s; return NULL; }
int dlclose(void *h) { (void)h; return 0; }
char *dlerror(void) { return NULL; }

/* ── Generated FFI symbol declarations and registration ───────────── */
#include "kunabi_ffi_symbols.h"

int main(int argc, char *argv[]) {
    char prog_path[256];
    int fd = -1;
    int use_tmpfile = 0;

#ifdef __linux__
    fd = memfd_create("kunabi-program", MFD_CLOEXEC);
    if (fd >= 0) {
        if (write(fd, kunabi_program_data, kunabi_program_size) != (ssize_t)kunabi_program_size) {
            perror("write memfd");
            close(fd);
            return 1;
        }
        snprintf(prog_path, sizeof(prog_path), "/proc/self/fd/%d", fd);
    } else {
        use_tmpfile = 1;
    }
#else
    use_tmpfile = 1;
#endif

    if (use_tmpfile) {
        const char *tmpdir = getenv("TMPDIR");
        if (!tmpdir) tmpdir = "/tmp";
        snprintf(prog_path, sizeof(prog_path), "%s/.kunabi-program-%d.so", tmpdir, getpid());
        FILE *fp = fopen(prog_path, "wb");
        if (!fp) { perror("fopen tmpfile"); return 1; }
        if (fwrite(kunabi_program_data, 1, kunabi_program_size, fp) != kunabi_program_size) {
            perror("fwrite tmpfile");
            fclose(fp);
            unlink(prog_path);
            return 1;
        }
        fclose(fp);
    }

    Sscheme_init(NULL);

    Sregister_boot_file_bytes("petite", (void*)petite_boot_data, petite_boot_size);
    Sregister_boot_file_bytes("scheme", (void*)scheme_boot_data, scheme_boot_size);
    Sregister_boot_file_bytes("kunabi", (void*)kunabi_boot_data, kunabi_boot_size);

    Sbuild_heap(NULL, NULL);

    /* Register FFI symbols AFTER heap is built, BEFORE loading program */
    register_ffi_symbols();

    int status = Sscheme_script(prog_path, argc, (const char **)argv);

    if (fd >= 0) close(fd);
    if (use_tmpfile) unlink(prog_path);
    Sscheme_deinit();
    return status;
}
